#!/usr/bin/env python3

from sh import file
from sh import git
from sh import shellcheck


def print_z(*args):
    print(*args, end='')


def mimetype(path):
    return file('--brief', '--mime-type', path).strip()


def is_shell_script(path):
    return path.endswith('.sh') \
        or (mimetype(path) == 'text/x-shellscript')


def list_files():
    out = git('diff', '-z',
              '--diff-filter=AMrcd',
              '--name-only',
              '--no-ext-diff',
              'HEAD~1',
              _tty_out=False)
    return filter(None, out.split('\0'))


def main():
    shell_scripts = filter(is_shell_script, list_files())
    for f in shell_scripts:
        shellcheck(f, _out=print_z, _ok_code=[0, 1])


if __name__ == "__main__":
    main()
