#!/usr/bin/env python3

import json
import re

from sh import file
from sh import git
from sh import shellcheck


def print_z(*args):
    print(*args, end='')


def mimetype(path):
    return file('--brief', '--mime-type', path).strip()


def is_shell_script(path):
    return path.endswith('.sh') \
        or (mimetype(path) == 'text/x-shellscript')


def extract_added_lines_ranges(diff_string):
    prog = re.compile('@@ [^ ]+ \+(\d+),?(\d+)?')
    for line in diff_string:
        if not line.startswith('@@'):
            continue
        n, offset = prog.match(line).groups()
        line_from = max(int(n), 1)
        line_to = line_from + int(offset or 0)
        yield (line_from, line_to)


def added_lines(file):
    out = git('diff', '-U0',
              '--ignore-space-at-eol',
              'HEAD~1',
              file,
              _tty_out=False)
    return extract_added_lines_ranges(out)


def list_files():
    out = git('diff', '-z',
              '--diff-filter=AMrcd',
              '--name-only',
              '--no-ext-diff',
              'HEAD~1',
              _tty_out=False)
    return filter(None, out.split('\0'))


def main():
    shell_scripts = filter(is_shell_script, list_files())
    for f in shell_scripts:
        print(f)
        print(list(added_lines(f)))
        j = json.loads(shellcheck('--format=json', f, _ok_code=[0, 1]).strip())
        print(json.dumps(j, indent=2))


if __name__ == "__main__":
    main()
